### ISSUE TITLE
Typo in RootStackNavigator.tsx

### ISSUE THREAD

**Issue by Iridahonda** [Duell10111/ReactTube#11]
Ignore - Schoolboy error by me

**Comment by Duell10111** [comment]
I found the typo in a file named wrong, which is only some issue eye issues and should not cause any issues while runtime.
Whatever it is fixed in this MR: :)
https://github.com/Duell10111/ReactTube/pull/12/files#diff-e85f5b6cc825db209ac4da51677617c9850e7da0eed08261d689cbb3d2dcc7a5
