### ISSUE TITLE
Language settable in app

### ISSUE THREAD

**Issue by Iridahonda** [Duell10111/ReactTube#15]
Awesome searchbar update! Although I have found one issue:

When using on a physical device you cannot enter any text using the normal ATV character select method via the remote.  Note audible/voice entry works fine.  

Any chance to add the yt language setting from the settings menu.

hooks/useYoutube.ts:

  Innertube.create({
      lang: "en",
    })

**Comment by Duell10111** [comment]
Thanks for the info.
I will look into it.

Regarding the language selection, I currently try to restructure the settings.
I will try to add this as a new feature. 😊

**Comment by Duell10111** [comment]
I found the issue you mentioned, but currently I am unsure how to fix this in the corresponding library, as the press is not completly working.
Pressing the search hints seems to work.
The keyboard otherwise not. 😅
I referenced the issue tracked in the new library.

**Comment by Duell10111** [comment]
@Iridahonda 
The TV remote issue on searchscreen will be fixed with https://github.com/Duell10111/ReactTube/pull/16

**Comment by Duell10111** [comment]
The language selection will come with this MR. :)

https://github.com/Duell10111/ReactTube/pull/19

**Comment by Duell10111** [comment]
Closed with MR #19
