### ISSUE TITLE
Confused on how to do LOCALBUILD

### ISSUE THREAD

**Issue by yodaluca23** [Duell10111/ReactTube#22]
I am stuck on this part:

* Go to the project settings and configure your reacttube target.
* Change the build configuration to Release in your schema.

This is what I see, what do I change?
<img width="1462" alt="image" src="https://github.com/Duell10111/ReactTube/assets/67206487/5d00fd9e-a6dd-403e-8e54-e7c8a670f6d0">

**Comment by yodaluca23** [comment]
Could you just make a pre-compiled .ipa?

**Comment by Duell10111** [comment]
> I am stuck on this part:
> 
> 
> 
> * Go to the project settings and configure your reacttube target.
> 
> * Change the build configuration to Release in your schema.
> 
> 
> 
> This is what I see, what do I change?
> 
> <img width="1462" alt="image" src="https://github.com/Duell10111/ReactTube/assets/67206487/5d00fd9e-a6dd-403e-8e54-e7c8a670f6d0">
> 
> 

I am currently unfortunately not on my computer, but you have to left click on the reacttube next to the tvOS downloading text of your image.
Afterwards you have to click on the edit schema button and there you can change your build configuration to release. :)

**Comment by Duell10111** [comment]
> Could you just make a pre-compiled .ipa?

It's planned to do this, but I just did not have time to integrate this in the GitHub CI

**Comment by Duell10111** [comment]
> Could you just make a pre-compiled .ipa?

I tried to build some ipas, but I am unsure if they work. :D

**Comment by yodaluca23** [comment]
> > Could you just make a pre-compiled .ipa?
> 
> 
> 
> I tried to build some ipas, but I am unsure if they work. :D

Ooo I'll have to try them, I did get it to work installing it from Xcode.

**Comment by Duell10111** [comment]
Will close this issue with the merge of https://github.com/Duell10111/ReactTube/pull/24. :)

**Comment by yodaluca23** [comment]
> > Could you just make a pre-compiled .ipa?
> 
> I tried to build some ipas, but I am unsure if they work. :D

I used this, and was able to successfully use them with sideloadly
https://github.com/timmiehaha/ipagen
Though, I would run this to re-enable Xcode code signing afterwards...
```
plutil -replace DefaultProperties.CODE_SIGNING_REQUIRED -string YES /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/SDKSettings.plist
```
