### ISSUE TITLE
Error: Failed to extract n-token decipher algorithm with   "youtubei.js": "10.2.0"

### ISSUE THREAD

**Issue by Iridahonda** [Duell10111/ReactTube#27]
I'm getting an error with the latest push.  Seems we need to update to 10.3.0 due to YT changes but that seems not to be trivial.

**Comment by Duell10111** [comment]
Yes indeed, I upgraded in my watch feature branch to v10.3.0 but it was quite a hustle.
But it seems to work now.
By time I will upgrade it on the main branch too. 😊
Otherwise the HLS player type should still work if you change to it in the settings. 😄

**Comment by Iridahonda** [comment]
I followed your downloader-backup changes and got it working. Thank you very much.  This is an excellent and fun app to learn a bit about react-native.

**Comment by Duell10111** [comment]
> I followed your downloader-backup changes and got it working. Thank you very much. This is an excellent and fun app to learn a bit about react-native.

That's great to hear. :)

Feel free to create a PR if you have new ideas or features to add. :D
